
export enum Types {
  APPARITION = "APPARITION",
  PSYCHOPHONY = "PSYCHOPHONY",
  HAUNTED_HOUSE = "HAUNTED_HOUSE",
  REINCARNATION = "REINCARNATION",
  TELEPATHY = "TELEPATHY",
  TELEKINESIS = "TELEKINESIS",
  UFOLOGY = "UFOLOGY",
}
